// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Token     string `json:"token"`
	ExpiresIn int64  `json:"expiresIn"`
}

type UserInfoReq struct {
}

type UserInfoResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Email    string `json:"email"`
}
